---
# tasks file for runner_install
- name: Install GitLab runner  dependencies
  apt:
    name: ['curl', 'ca-certificates', 'tzdata','openssl', 'gnupg2', 'rsync', 'git', 'libcurl3-gnutls', 'liberror-perl', 'git-man']
    state: present

#- name: Download package
#  command: "curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash"
#  command: "curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash"
#  get_url:
#    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
#    dest: /home/ubuntu/script.deb.sh
#    url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb
#    dest: /home/ubuntu/gitlab-runner_amd64.deb

#- name: Install repository
#  command: "bash /home/ubuntu/script.deb.sh"

- name: Install gitlab runner
  apt:
    deb: https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb
    state: present

- name: Copy id_rsa to runner node
  copy:
    src: id_rsa
    dest: /home/ubuntu/.ssh/id_rsa
    owner: ubuntu
    group: ubuntu
    mode: '0600'

- name: Register gitlab-runner
  command: "gitlab-runner register --non-interactive --url {{GitLabURL}} --registration-token {{GitLabToken}} --executor \"shell\""