---
#- name: Update apt-get repo and cache
#  apt:
#    update_cache=yes
#    force_apt_get=yes
#- name: Upgrade all apt packages
#  apt:
#    upgrade=dist
#    force_apt_get=yes

# tasks file for nginx
- name: Install Nginx Web Server on Debian Family
  apt:
    name=nginx
    state=latest
  notify:
    - start nginx
#- name: Replace nginx.conf
#  template:
#    src=templates/nginx.conf
#    dest=/etc/nginx/nginx.conf
- name: Add Virtual Hosts Config
  template:
    src: nginx_vhosts.conf
    dest: /etc/nginx/sites-available/{{ item.key }}.conf
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ nginx_sites }}"
- name: Enable Site Config
  file:
    src: /etc/nginx/sites-available/{{ item.key }}.conf
    dest: /etc/nginx/sites-enabled/{{ item.key }}
    state: link
  with_dict: "{{ nginx_sites }}"
  notify: reload nginx
- name: Install certbot plugin for nginx from repository
  apt:
    name: 
      python3-certbot-nginx
    state: present
- name: Generate certs
  command: |
    certbot -d {{ item.value.domains | join(' -d ') }}
    certonly
    --nginx
    --email {{ item.value.letsencrypt_email }}
    --non-interactive --agree-tos 
#    --test-cert
  with_dict: "{{ nginx_sites }}"
  when: item.value.letsencrypt | default(False)
- name: Replace Site Config with SSL options
  template:
    src: nginx_vhosts_ssl.conf
    dest: /etc/nginx/sites-available/{{ item.key }}.conf
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ nginx_sites }}"
  notify: reload nginx
