---
# handlers file for apache
- name: start apache
  systemd:
    name: apache2
    enabled: yes
    state: started

- name: reload apache
  service:
    name: apache2
    state: reloaded

- name: restart apache
  service:
    name: apache2
    state: restarted