---
# tasks file for hostname_set
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
- name: add myself to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ inventory_hostname }}'
    state: present